version: '3.8'

services:
  codesync-backend:
    build: .
    container_name: codesync_api
    restart: always 
    ports:
      - "7000:7000" 
      - "1234:1234"
    env_file:
      - .env
    volumes:
      - ./public/temp:/app/public/temp